apiVersion v1
kind Service
metadata
  name prometheus
  labels
    name prometheus
spec
  ports
  - name prometheus
    protocol TCP
    port 9090
    targetPort 9090
  selector
    app prometheus
  type NodePort
---
apiVersion extensionsv1beta1
kind Deployment
metadata
  labels
    name prometheus
  name prometheus
spec
  replicas 1
  template
    metadata
      labels
        app prometheus
    spec
      serviceAccountName: prometheus
      serviceAccount: prometheus
      containers
      - name prometheus
        image promprometheusv2.9.0
        command
        - binprometheus
        args
        - --config.file=etcprometheusprometheus.yml
        ports
        - containerPort 9090
          protocol TCP
        volumeMounts
        - mountPath etcprometheus
          name prometheus-config
      volumes
      - name prometheus-config
        configMap
          name prometheus-config